apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: flask_app_db
        - name: MYSQL_USER
          value: flask_app_user
        - name: MYSQL_PASSWORD
          value: flask_app_password
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: your-flask-app-image:latest
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: flask_app_db
        - name: MYSQL_USER
          value: flask_app_user
        - name: MYSQL_PASSWORD
          value: flask_app_password
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  frontend-app.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>User List App</title>
    </head>
    <body>

    <h1>User List</h1>
    <ul id="user-list"></ul>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Fetch users from the backend API
            fetch('http://flask-app-service:5000/users')
                .then(response => response.json())
                .then(users => {
                    // Update the user list in the HTML
                    const userListElement = document.getElementById('user-list');
                    users.forEach(user => {
                        const listItem = document.createElement('li');
                        listItem.textContent = `${user.id}: ${user.name}`;
                        userListElement.appendChild(listItem);
                    });
                })
                .catch(error => console.error('Error fetching users:', error));
        });
    </script>

    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: frontend-config
        configMap:
          name: frontend-config
